$(document).ready(function(){
   $('.page2_column').click(function(event){
      $('.page2_column').toggleClass('down');
   });
   $('.page2_column').click(function(event){
      $('.page2_column2').toggleClass('down');
   });
   $('.page2_column').click(function(event){
      $('.page2_column3').toggleClass('down');
   });
   $('.page2_column').click(function(event){
      $('.page2_column4').toggleClass('down');
   });
});

$(document).ready(function(){
   $('.page2_column2').click(function(event){
      $('.page2_column').toggleClass('down');
   });
});
